# Generated by Django 5.1.1 on 2024-09-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_watches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='watches',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='watches',
            name='date',
            field=models.DateField(verbose_name='Watch date'),
        ),
    ]
