# Generated by Django 5.1.1 on 2024-09-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rating_alter_watches_options_alter_watches_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ratings',
            field=models.ManyToManyField(to='main_app.rating'),
        ),
    ]
